### ISSUE TITLE
Change tracking does not log any changes when a record is updated via UPSERT

### ISSUE THREAD

**Issue by jbm1991** [cap-js/change-tracking#136]
If you use `UPSERT` in a service handler to update a record then no changes are logged. This means you have to manually work out if an UPDATE or INSERT should be used, and then use the correct one. It would be great if UPSERT could also be handled.

**Comment by nkaputnik** [comment]
Hello @jbm1991 
the change-tracking plugin is using a build-in CAP function called `req.diff`, which is unsuported for UPSERT. 
Therefore, we're unable to support UPSERT in this plugin.
We also checked with other plugins (Audit-Logging), and they face the same limitation.
Unfortunately, we have no means to re-create the req.diff functionality ourselves, given our resource situation, and since UPSERT is ambivalent and could create either an INSERT or UPDATE diff, based on context.

Best,
Nick

**Comment by jbm1991** [comment]
Hi Nick,

Thanks for investigating and the explanation.

Thanks
John

**Comment by PierreFritsch** [comment]
Hi team (tagging @stefanrudi & @schiwekM re. https://github.com/cap-js/change-tracking/pull/216),

with v2.0.0 now released, the change tracking mechanism has been fundamentally [reworked](https://github.com/cap-js/change-tracking/blob/main/CHANGELOG.md#version-200---2026-06-12) to use database-level triggers rather than CAP event handlers and `req.diff`. Since the original blocker for UPSERT support was the lack of `req.diff` support, would it be worth revisiting whether UPSERT support would be an option?
