### ISSUE TITLE
Value Fields are too Small for our Application Content

### ISSUE THREAD

**Issue by alexandrahofmann01** [cap-js/change-tracking#50]
Hi,

in our application we have to log certain fields to store their history. 
One field might have values in there that are larger than 5.000 characters which is the size of a String field defined in the CAP Framework.
Therefore, to make it possible to track this field with the change history, the field ["valueChangedFrom" and "valueChangedTo" from the entity "Changes"](https://github.com/cap-js/change-tracking/blob/main/index.cds#L58-L59) would need to be upgraded from type String to LargeString.

**Comment by nkaputnik** [comment]
Hello @alexandrahofmann01 

first of all: Are you sure you want to fully change-track Elements having more than 5k Characters? The Change-Tracking Plugin is using 2 tables as Master/Detail (Composition) for logging, meaning that each LargeString Change will create a huge overhead in the Database. If this happens regularly, the detail table may grow uncomfortably large and impact the overall application performance.

If you really want to do this, you can remediate this by manually adjusting the data type of the attribute in your project.
The data type is defined in 
`namespace sap.changelog;`
as

```cds
entity Changes {
      key ID                : UUID                     @UI.Hidden;
      ...
      valueChangedFrom  : String                   @title: '{i18n>Changes.valueChangedFrom}';
      valueChangedTo    : String                   @title: '{i18n>Changes.valueChangedTo}';
      ...
};
```

in `index.cds` in the root of the change-tracking plugin.
If you clone the change-tracking plugin and use the workspaces technology (as exemplified in the CAP Samples Bookshop setup) instead of `npm install`, you can be sure that your change is surviving upgrades of the plugin when doing a `GIT pull` rather than an `npm install`

Best,
Nick

**Comment by alexandrahofmann01** [comment]
Thanks for the hint, we will definitely look into that. I am aware that this might influence the performance and we have to discuss this within our team agains the business requirements.
