### ISSUE TITLE
SAP Fiori Elements Localization (@i18n) not working properly with @changelog

### ISSUE THREAD

**Issue by jbibal-pdc** [cap-js/change-tracking#55]
Hello,

The plugin doesn't seem to properly recognize **i18n** texts as needed for localization.

Following the guide from SAP: **[Localization of UI Texts](https://sapui5.hana.ondemand.com/sdk/#/topic/b8cb649973534f08a6047692f8c6830d)**

We assigned the `status` field the `@Common.Label` annotation as seen below:  
![image](https://github.com/cap-js/change-tracking/assets/105326887/1f1a1c61-66c4-45f7-ac3e-969e7e444112)

However, the localized text isn't getting rendered properly.
![image](https://github.com/cap-js/change-tracking/assets/105326887/caca115f-676a-4c49-9720-1edb6c09800c)

Not sure what I am doing wrong. I also tried `@changelog: ['{@i18n>status}']`, but to no avail.

Hoping for your feedback.

Thanks,
John

**Comment by nkaputnik** [comment]
Hello @jbibal-pdc 
can you take a look whether this answer here also fixes your issue?
https://github.com/cap-js/change-tracking/issues/48

**Comment by JocelynGu135** [comment]
Hi @jbibal-pdc,

I have reproduced this issue in my local.

And I find the reason why not showing the localized text is because of the incorrect definition for i18n.

**For your sample:**
`status: @Common : {Label: '{@18n>status}'}  @changelog`

**Correct definition:**
`status: @Common : {Label: '{18n>status}'}  @changelog`

There is no need to add **@** before i18n.

Hope this will fix your issue. If you encounter any other problems, please let us know. 

Best Regards
Jocelyn
