### ISSUE TITLE
@cap-js/change-tracking: change logs are not captured

### ISSUE THREAD

**Issue by wildflowerr1** [cap-js/change-tracking#64]
Changing "@sap/cds": "6.5.0" to "@sap/cds": "7.5.2".
Before the cds upgrade we used @sap/cap-change-history.
With cds > 7 we thrive for @cap-js/change-tracking instead.

I was able to configure and run everything written for the incidents-app [here](https://github.com/cap-js/change-tracking) . However, when applying the exact same steps within our project, I do not see Change History facet automatically added to the Fiori Object Page of my annotated entity. Thus, no changeLog is captured at all.

In the following pictures you will see proper entity level annotations and missing facet over the respective object page:
<img width="674" alt="image" src="https://github.com/cap-js/change-tracking/assets/156909896/40007d80-8b3c-434c-b5a2-adace6834755">

<img width="1732" alt="image" src="https://github.com/cap-js/change-tracking/assets/156909896/8090a96b-e6ca-4102-88af-49609c47ca44">

**Comment by JocelynGu135** [comment]
Hi @wildflowerr1 ,

The root cause is that some issues for cds plugins in @sap/cds 7.5.2.
 
So two ways to avoid this issue:
1. Use @sap/cds 7.5.3
2. If @sap/cds 7.5.2 is necessary. Add the following code in package.json
<img width="428" alt="image" src="https://github.com/cap-js/change-tracking/assets/132032144/03a07cb1-d324-4a17-8f70-d2ea0c722719">

After that, the “Change History” can be displayed as expected result.
<img width="1662" alt="image" src="https://github.com/cap-js/change-tracking/assets/132032144/4dd26e66-e160-4a14-97a2-1254ff0e5fcd">

Best Regards
Jocelyn

**Comment by JocelynGu135** [comment]
After confirmed with @wildflowerr1. @cap-js/change-tracking was able to run. So closed the issue.
