### ISSUE TITLE
Question: updates from a background job

### ISSUE THREAD

**Issue by wozjac** [cap-js/change-tracking#94]
Hi, would the plugin track the changes in the given scenario:

- annotations `changelog` added to the model.cds (DB layer)
- then the tables with annotations projected in various services
- in `server.js` a process is spawn, which uses cron for node.js. This process does updates via db layer, not service layer - `UPDATE(dbtable)`... 

Will such updates be tracked as well? 

BR,
Jacek

**Comment by nkaputnik** [comment]
Hello @wozjac 
the change tracking only works on Application Service level, meaning pure DB layer calls won't get tracked.
This shouldn't be any issue at all in your scenario, though, since you can easily route all your calls through application service level entities (in CAP, this would mean zero overhead, too), instead of DB calls. Even the syntax is the same. If your DB entitiy isn't exposed with the necessary projection yet, simply create a technical service (with cds.api.ignore you can conveniently hide it from the OData metadata).
Please be aware that for a spawned process to work with a CAP plugin, the spawned process itself also needs to be a CAP runtime with the Plugin installed.

Best,
Nick
